### ISSUE TITLE
The doc is not complete

### ISSUE THREAD

**Issue by lxtGH** [pmeletis/panoptic_parts#14]
Hi! It is an interesting work. @DdeGeus @vincentwen1995 

In the page of Generate part-aware panoptic segmentation results.

I can not download the part segmentation results via one drive. 

Could you check it?

Also 
The link to how to prefrom evaluation is broken.

**Comment by DdeGeus** [comment]
Hi! Thank you for your interest in our work.

Could you tell me what problem you run into exactly when you want to download the part segmentation results? I cannot find the issue. When I follow [this link](https://1drv.ms/u/s%21AojlpuGgPtL1bqHeflaWtk24UY0?e=Sr2BOX), I am able to download the zip file.

As for the link to the evaluation, indeed it seems that there is a broken link. You can find the evaluation details here: https://panoptic-parts.readthedocs.io/en/stable/evaluate_results.html

**Comment by pmeletis** [comment]
Thank you @lxtGH.
We fixed the broken link and have updated it with Baidu cloud storage for some regions of the world that cannot access one drive.
Thus I close this issue.
