### ISSUE TITLE
How to merge Semantic segmentation and Part segmentation?

### ISSUE THREAD

**Issue by moddent** [pmeletis/panoptic_parts#17]
Hi, there:

I want to merge Semantic segmentation and Part segmentation to generate the new label in .png format.

Can you give me some suggestion or some references.

Thx.

**Comment by pmeletis** [comment]
Hello moddent,
Currently, there is documentation to merge semantic and instance segmentation, and panoptic and part segmentation, but not semantic and part segmentation. We are planning to provide a script for that as well, so the semantic-part ids (_sids_pids_) can be generated and evaluated. For now, you can use the docs [here](https://panoptic-parts.readthedocs.io/en/stable/generate_results.html#merge-panoptic-and-part-segmentation-to-pps) by encoding your semantic segmentation as panoptic segmentation. @DdeGeus other suggestions?

**Comment by DdeGeus** [comment]
Hi @moddent, thanks for your interest in our work!

For what purpose do you want to use this exactly? If you want to generate just the semantic segmentation (stuff) and part segmentation (part) labels from our ground-truth, you can just use the _sids_ and _pids_ only when decoding the ground-truth as described [here](https://panoptic-parts.readthedocs.io/en/stable/api_and_code.html).

If you wish to merge semantic segmentation and part segmentation predictions as a 3-channel PNG as described [here](https://panoptic-parts.readthedocs.io/en/stable/generate_results.html), you can simply treat all scene classes as _stuff_ classes, as @pmeletis suggested, and follow the entire merging procedure. For merging to the 3-channel format, you just have to change the _stuff_ class definition in the EvalSpec described [here](https://panoptic-parts.readthedocs.io/en/stable/generate_results.html#evalspec). 

Does this answer your question?
