### ISSUE TITLE
panoptic_parts.safe_write function increases file size drastically

### ISSUE THREAD

**Issue by PPAvBerlo** [pmeletis/panoptic_parts#25]
Hello, I have been using the `panoptic_parts.safe_write()` function but after opening a file, decoding it using `panoptic_parts.utils.format.decode_uids()`, encoding it using`panoptic_parts.utils.format.encode_ids()` and saving it with `panoptic_parts.safe_write()` the file size increases by a factor of 15. Using `import tifffile` and `tifffile.imwrite(path/to/file, encoded_file, compression = 'zlib')` to save the ground truth the file stays the same or even decreases in size. The contents of the file remains intact and is usable without any issues.

**Comment by pmeletis** [comment]
Hi Pim, now you can pass parameters to the underline image writer using keyword arguments in `safe_write`. Initially, this function was designed for writing results, but with the new feature, it can also write ground truth files. Moreover, I tested it also with the previous implementation and it was by default compressing pngs (using Pillow >=8.0.0). `safe_write` and `tifffile.imwrite` produce same size images.
