### ISSUE TITLE
Undocumented part label 5 for person and rider (Cityscapes)

### ISSUE THREAD

**Issue by qizhuli** [pmeletis/panoptic_parts#8]
I downloaded a fresh copy of the dataset from the Cityscapes official website yesterday. While I was processing the data, I found that there seemed to be an undocumented part label 5 for the person and rider class. These are the images that have it:
```
munster_000033_000019_gtFinePanopticParts.tif: (person, 5)
munster_000035_000019_gtFinePanopticParts.tif: (person, 5)
munster_000046_000019_gtFinePanopticParts.tif: (person, 5)
munster_000047_000019_gtFinePanopticParts.tif: (person, 5), (rider, 5)
munster_000048_000019_gtFinePanopticParts.tif: (person, 5)
munster_000052_000019_gtFinePanopticParts.tif: (person, 5)
munster_000055_000019_gtFinePanopticParts.tif: (person, 5)
munster_000057_000019_gtFinePanopticParts.tif: (person, 5)
munster_000058_000019_gtFinePanopticParts.tif: (person, 5)
```
where `(person, 5)` and `(rider, 5)` means there is at least one pixel with the semantic class `person` and `rider`, respectively, and a part label of 5. Upon a quick glance, they seem to correspond to personal accessories and belongings in the images.

I guess it would be better to document them, just to avoid unwanted surprises for dataset users.

**Comment by pmeletis** [comment]
Any possible ids outside the valid range are automatically handled in v2 release of the code and they are mapped to the ignored class. Thank you for pointing this out.
